//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTimecard.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SimpleTimecard.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        internal static string ButtonRegist {
            get {
                return ResourceManager.GetString("ButtonRegist", resourceCulture);
            }
        }
        
        internal static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        internal static string ButtonSetting {
            get {
                return ResourceManager.GetString("ButtonSetting", resourceCulture);
            }
        }
        
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        internal static string ButtonRegistStartTime {
            get {
                return ResourceManager.GetString("ButtonRegistStartTime", resourceCulture);
            }
        }
        
        internal static string ButtonRegistEndTime {
            get {
                return ResourceManager.GetString("ButtonRegistEndTime", resourceCulture);
            }
        }
        
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        internal static string LabelToday {
            get {
                return ResourceManager.GetString("LabelToday", resourceCulture);
            }
        }
        
        internal static string LabelList {
            get {
                return ResourceManager.GetString("LabelList", resourceCulture);
            }
        }
        
        internal static string LabelStartTime {
            get {
                return ResourceManager.GetString("LabelStartTime", resourceCulture);
            }
        }
        
        internal static string LabelEndTime {
            get {
                return ResourceManager.GetString("LabelEndTime", resourceCulture);
            }
        }
        
        internal static string LabelStartTimeColon {
            get {
                return ResourceManager.GetString("LabelStartTimeColon", resourceCulture);
            }
        }
        
        internal static string LabelEndTimeColon {
            get {
                return ResourceManager.GetString("LabelEndTimeColon", resourceCulture);
            }
        }
        
        internal static string LabelRegistDate {
            get {
                return ResourceManager.GetString("LabelRegistDate", resourceCulture);
            }
        }
    }
}
